######################################################################
# Automatically generated by qmake (2.01a) dim. sept. 23 18:52:26 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += vertices.h
SOURCES += main.cpp vertices.cpp
